// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"NakedVPN/internal/biz"
	"NakedVPN/internal/conf"
	"NakedVPN/internal/data"
	"NakedVPN/internal/server"
	"NakedVPN/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, logger)
	httpServer := server.NewHTTPServer(confServer, logger)
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	organizeRepo := data.NewOrganizeRepo(dataData, logger)
	organizeUseCase := biz.NewOrganizeUseCase(organizeRepo, logger)
	streamProcessing := service.NewStreamProcessing(organizeUseCase, logger)
	netServer := server.NewNetServer(streamProcessing, confServer, logger)
	app := newApp(logger, grpcServer, httpServer, netServer)
	return app, func() {
		cleanup()
	}, nil
}
